name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - backend/**

env:
  IMAGE_NAME: pokemon-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Build Matrix
        run: |
          echo "TAG_IMAGE=${{ env.IMAGE_NAME }}_${{ github.run_id }}_${{ github.sha }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG_IMAGE} -f ./backend/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG_IMAGE}
          echo "La imagen ${{ env.IMAGE_NAME }} se subió correctamente a Docker Hub"

  update:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH Key and Git Config
        run: |
          echo "Starting update manifest job"
          sudo apt-get install -y git
          mkdir -p ~/.ssh
          echo "${{ secrets.GIT_SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          git config --global user.name "${{ secrets.GIT_USER_NAME }}" 
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Clone Repository
        run: git clone --single-branch --branch main git@github.com:pablo-de/cicd-example.git

      - name: Update Manifest
        run: |
          cd helm/pokemon-app/
          sed -i "s/\(tag:\).*/\1 ${TAG_IMAGE}/g" values.yaml
          cat values.yaml
          cd ../..
          git add .
          git commit -m "update tag ${TAG_IMAGE}"
          git push origin git@github.com:pablo-de/cicd-example.git

